site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

nav:
  - 'Current 2.11':
    - Introduction: 'current/introduction.md'
    - Quickstart: 'current/quickstart.md'
    - Tutorials:
      - 'tutorials/README.md'
      - Word Count: 'current/tutorials/word-count/tutorial.md'
      - Anomaly Detection: 'current/tutorials/anomaly-detection/tutorial.md'
      - Purchase Filtering: 'current/tutorials/purchase-filtering/tutorial.md'
    - How to:
      - Produce Data to Kafka: 'current/producer.md'
      - Process & Transform Data: 'current/processing.md'
      - GroupBy Operation: 'current/groupby.md'
      - Windows & Aggregations: 'current/windowing.md'
      - Configuration: 'current/configuration.md'
    - Advanced Usage:
      - Checkpointing: 'current/advanced/checkpointing.md'
      - Serialization Formats: 'current/advanced/serialization.md'
      - Schema Registry: 'current/advanced/schema-registry.md'
      - Stateful Processing: 'current/advanced/stateful-processing.md'
      - Managing Kafka Topics: 'current/advanced/topics.md'
      - Using Producer & Consumer: 'current/advanced/producer-consumer-lowlevel.md'
      - StreamingDataFrame Assignment Rules: 'current/advanced/dataframe-assignments.md'
    - Connecting to Quix Cloud: 'current/quix-platform.md'
    - 'Connectors [beta]':
      -  Sinks:
          - 'connectors/sinks/README.md'
          - CSV Sink: 'current/connectors/sinks/csv-sink.md'
          - InfluxDB v3 Sink: 'current/connectors/sinks/influxdb3-sink.md'
          - Creating a Custom Sink: 'current/connectors/sinks/custom-sinks.md'
      - Sources:
          - 'connectors/sources/README.md'
          - CSV Source: 'current/connectors/sources/csv-source.md'
          - Kafka Replicator Source: 'current/connectors/sources/kafka-source.md'
          - Quix Source: 'current/connectors/sources/quix-source.md'
          - Creating a Custom Source: 'current/connectors/sources/custom-sources.md'
    - Upgrading Guide:
      - Upgrading from Quix Streams v0.5: 'current/upgrading-legacy.md'
    - API Docs:
      - StreamingDataFrame API: 'current/api-reference/dataframe.md'
      - Topics API: 'current/api-reference/topics.md'
      - Context API: 'current/api-reference/context.md'
      - Serializers API: 'current/api-reference/serialization.md'
      - Application API: 'current/api-reference/application.md'
      - State API: 'current/api-reference/state.md'
      - Kafka Producer & Consumer API: 'current/api-reference/kafka.md'
      - Sources API: 'current/api-reference/sources.md'
      - Sinks API: 'current/api-reference/sinks.md'
      - Kafka Producer & Consumer API: 'current/api-reference/kafka.md'
      - Full Reference: 'current/api-reference/quixstreams.md'

  - 'Previous 2.0-2.10':
    - Introduction: 'previous/introduction.md'
    - Quickstart: 'previous/quickstart.md'
    - Tutorials:
      - 'tutorials/README.md'
      - Word Count: 'previous/tutorials/word-count/tutorial.md'
      - Anomaly Detection: 'previous/tutorials/anomaly-detection/tutorial.md'
      - Purchase Filtering: 'previous/tutorials/purchase-filtering/tutorial.md'
    - How to:
      - Produce Data to Kafka: 'previous/producer.md'
      - Process & Transform Data: 'previous/processing.md'
      - GroupBy Operation: 'previous/groupby.md'
      - Windows & Aggregations: 'previous/windowing.md'
      - Configuration: 'previous/configuration.md'
    - Advanced Usage:
      - Checkpointing: 'previous/advanced/checkpointing.md'
      - Serialization Formats: 'previous/advanced/serialization.md'
      - Schema Registry: 'previous/advanced/schema-registry.md'
      - Stateful Processing: 'previous/advanced/stateful-processing.md'
      - Managing Kafka Topics: 'previous/advanced/topics.md'
      - Using Producer & Consumer: 'previous/advanced/producer-consumer-lowlevel.md'
      - StreamingDataFrame Assignment Rules: 'previous/advanced/dataframe-assignments.md'
    - Connecting to Quix Cloud: 'previous/quix-platform.md'
    - 'Connectors [beta]':
      -  Sinks:
          - 'connectors/sinks/README.md'
          - CSV Sink: 'previous/connectors/sinks/csv-sink.md'
          - InfluxDB v3 Sink: 'previous/connectors/sinks/influxdb3-sink.md'
          - Creating a Custom Sink: 'previous/connectors/sinks/custom-sinks.md'
      - Sources:
          - 'connectors/sources/README.md'
          - CSV Source: 'previous/connectors/sources/csv-source.md'
          - Kafka Replicator Source: 'previous/connectors/sources/kafka-source.md'
          - Quix Source: 'previous/connectors/sources/quix-source.md'
          - Creating a Custom Source: 'previous/connectors/sources/custom-sources.md'
    - Upgrading Guide:
      - Upgrading from Quix Streams v0.5: 'previous/upgrading-legacy.md'
    - API Docs:
      - StreamingDataFrame API: 'previous/api-reference/dataframe.md'
      - Topics API: 'previous/api-reference/topics.md'
      - Context API: 'previous/api-reference/context.md'
      - Serializers API: 'previous/api-reference/serialization.md'
      - Application API: 'previous/api-reference/application.md'
      - State API: 'previous/api-reference/state.md'
      - Kafka Producer & Consumer API: 'previous/api-reference/kafka.md'
      - Sources API: 'previous/api-reference/sources.md'
      - Sinks API: 'previous/api-reference/sinks.md'
      - Kafka Producer & Consumer API: 'previous/api-reference/kafka.md'
      - Full Reference: 'previous/api-reference/quixstreams.md'
