site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

nav:
 - Current:
    - Introduction: 'introduction.md'
    - Quickstart: 'quickstart.md'
    - Tutorials:
      - 'tutorials/README.md'
      - Word Count: 'tutorials/word-count/tutorial.md'
      - Anomaly Detection: 'tutorials/anomaly-detection/tutorial.md'
      - Purchase Filtering: 'tutorials/purchase-filtering/tutorial.md'
    - How to:
      - Produce Data to Kafka: producer.md
      - Process & Transform Data: processing.md
      - GroupBy Operation: groupby.md
      - Windows & Aggregations: windowing.md
      - Configuration: configuration.md
    - Advanced Usage:
      - Checkpointing: advanced/checkpointing.md
      - Serialization Formats: advanced/serialization.md
      - Schema Registry: advanced/schema-registry.md
      - Stateful Processing: advanced/stateful-processing.md
      - Managing Kafka Topics: advanced/topics.md
      - Using Producer & Consumer: advanced/producer-consumer-lowlevel.md
      - StreamingDataFrame Assignment Rules: advanced/dataframe-assignments.md
    - Connecting to Quix Cloud: quix-platform.md
    - 'Connectors [beta]':
      -  Sinks:
          - 'connectors/sinks/README.md'
          - CSV Sink: connectors/sinks/csv-sink.md
          - InfluxDB v3 Sink: connectors/sinks/influxdb3-sink.md
          - Creating a Custom Sink: connectors/sinks/custom-sinks.md
      - Sources:
          - 'connectors/sources/README.md'
          - CSV Source: connectors/sources/csv-source.md
          - Kafka Replicator Source: connectors/sources/kafka-source.md
          - Quix Source: connectors/sources/quix-source.md
          - Creating a Custom Source: connectors/sources/custom-sources.md
    - Upgrading Guide:
      - Upgrading from Quix Streams v0.5: upgrading-legacy.md

    - API Docs:
      - StreamingDataFrame API: api-reference/dataframe.md
      - Topics API: api-reference/topics.md
      - Context API: api-reference/context.md
      - Serializers API: api-reference/serialization.md
      - Application API: api-reference/application.md
      - State API: api-reference/state.md
      - Kafka Producer & Consumer API: api-reference/kafka.md
      - Sources API: api-reference/sources.md
      - Sinks API: api-reference/sinks.md
      - Kafka Producer & Consumer API: api-reference/kafka.md
      - Full Reference: api-reference/quixstreams.md
 - Previous:
    - Introduction: 'previous/introduction.md'
    - Quickstart: 'previous/quickstart.md'
    - Tutorials:
      - 'previous/tutorials/README.md'
      - Word Count: 'previous/tutorials/word-count/tutorial.md'
      - Anomaly Detection: 'previous/tutorials/anomaly-detection/tutorial.md'
      - Purchase Filtering: 'previous/tutorials/purchase-filtering/tutorial.md'
    - How to:
      - Produce Data to Kafka: previous/producer.md
      - Process & Transform Data: previous/processing.md
      - GroupBy Operation: previous/groupby.md
      - Windows & Aggregations: previous/windowing.md
      - Configuration: previous/configuration.md
    - Advanced Usage:
      - Checkpointing: previous/advanced/checkpointing.md
      - Serialization Formats: previous/advanced/serialization.md
      - Schema Registry: previous/advanced/schema-registry.md
      - Stateful Processing: previous/advanced/stateful-processing.md
      - Managing Kafka Topics: previous/advanced/topics.md
      - Using Producer & Consumer: previous/advanced/producer-consumer-lowlevel.md
      - StreamingDataFrame Assignment Rules: previous/advanced/dataframe-assignments.md
    - Connecting to Quix Cloud: previous/quix-platform.md
    - 'Connectors [beta]':
      -  Sinks:
          - 'previous/connectors/sinks/README.md'
          - CSV Sink: previous/connectors/sinks/csv-sink.md
          - InfluxDB v3 Sink: previous/connectors/sinks/influxdb3-sink.md
          - Creating a Custom Sink: previous/connectors/sinks/custom-sinks.md
      - Sources:
          - 'previous/connectors/sources/README.md'
          - CSV Source: previous/connectors/sources/csv-source.md
          - Kafka Replicator Source: previous/connectors/sources/kafka-source.md
          - Quix Source: previous/connectors/sources/quix-source.md
          - Creating a Custom Source: previous/connectors/sources/custom-sources.md
    - Upgrading Guide:
      - Upgrading from Quix Streams v0.5: upgrading-legacy.md

    - API Docs:
      - StreamingDataFrame API: api-reference/dataframe.md
      - Topics API: api-reference/topics.md
      - Context API: api-reference/context.md
      - Serializers API: api-reference/serialization.md
      - Application API: api-reference/application.md
      - State API: api-reference/state.md
      - Kafka Producer & Consumer API: api-reference/kafka.md
      - Sources API: api-reference/sources.md
      - Sinks API: api-reference/sinks.md
      - Kafka Producer & Consumer API: api-reference/kafka.md
      - Full Reference: api-reference/quixstreams.md
