site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

# TODO: Replace //LINK placeholders everywhere
nav:
  - Introduction: 'introduction.md'
  - Quickstart: 'quickstart.md'
  - Producing Data to Kafka: producer.md
  - Processing & Transforming Data: processing.md
  - Windows & Aggregations: 'windowing.md'
  - Running the Application: application.md # TODO: Application configuration, error handling, logging, stopping the app.
  - Advanced Usage:
    - Serialization Formats: advanced/serialization.md
    - Stateful Processing: advanced/stateful-processing.md
    - Using Topics: advanced/topics.md # TODO: using topics, configuration, timestamp extraction
  - Connecting to Quix Cloud: quix-platform.md # TODO: Review, briefly explain Quix features & where Quix Cloud may help
  - Upgrading Guide:
    - Upgrading from Quix Streams v0.5: upgrading-legacy.md

  - API Docs:
    - StreamingDataFrame & StreamingSeries: api-reference/dataframe.md
    - Topics & Serializers: api-reference/topics-serdes.md  # TODO: Fix them
    - Application: api-reference/application.md
    - Producer & Consumer: api-reference/producer-consumer.md # TODO: Explain low-level producer and consumer
    - Full Reference: api-reference/quixstreams.md
