site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

#nav:
#  - 'Introduction': 'introduction.md'
#  - Example Applications: example.md
#  - Defining your Streaming Pipeline: streamingdataframe.md
#  - Windowed Aggregations: windowing.md
#  - Serialization: serialization.md
#  - Stateful Processing: stateful-processing.md
#  - Working with Quix:
#    - Using the Platform: quix-platform.md
#    - Upgrading from Quix Streams v0.5: upgrading-legacy.md
#  - API Docs:
#    - Application: api-reference/application.md
#    - StreamingDataFrame & Series: api-reference/dataframe.md
#    - Topics & Serializers: api-reference/topics-serdes.md
#    - Quix Platform API: api-reference/quix-platform-api.md
#    - Full Reference: api-reference/quixstreams.md


nav:
  - Introduction: 'introduction.md'
  - Quickstart: 'quickstart.md'
  - Producing Data to Kafka: producer.md
  - Processing & Transforming Data: processing.md
#    - Intro to StreamingDataFrame: '/#introduction-to-streamingdataframe'
#    - Transforming Data: '...'
#    - Updating Data In-Place: '...'
#    - Filtering: '...'
#    - Debugging: '...'
  - Windows & Aggregations: 'windowing.md'
#      - What Are Windows?
#      - Windows Examples
#      - Types of Time in Streaming
#      - Tumbling Windows
#      - Hopping Windows
#      - Lateness and Out-of-Order Processing
#      - Aggregations
#      - Emitting Results
#      - Operations Notes?  # TODO: The name can be better
  - Running the Application: application.md # TODO: Application configuration
#    - Configuration: '...'
#    - Error Handling: '...'
#    - Stopping the Application: '...'
#    - Logging: '...'
#
  - Advanced Usage:
#    - Serializers & Deserializers: serialization.md
    - Stateful Processing: stateful-processing.md
#      - State Configuration
#      - Fault Tolerance & Recovery
#      - Resetting the State
#    - Creating & Managing Topics: '...' # TODO: Auto-create topics, topic configs
#    - Extracting Timestamps from Events: '...' # TODO: timestamp extraction
#    - Using Producer & Consumer: '...'
  - Using with Quix Platform: quix-platform.md
#    - Quix Platform Overview: '...' # TODO: Briefly explain Quix features & why do you need to use Quix at all
#    - Connecting to Quix Platform brokers locally: quix-cloud/connecting-locally.md
#    - Visualizing Data in Quix Platform: # TODO: Using Quix format, charts. IMO, the most valuable Quix feature
#  - Examples: example.md # TODO: A link to Github "examples" folder with a nice README
  - Upgrading Guide:
    - Upgrading from Quix Streams v0.5: upgrading-legacy.md
#
  - API Docs:
    - Application: api-reference/application.md
    - StreamingDataFrame & StreamingSeries: api-reference/dataframe.md
    - Topics & Serializers: api-reference/topics-serdes.md  # TODO: Fix them
    - Producer & Consumer: api-reference/producer-consumer.md # TODO: Explain low-level producer and consumer
    - Full Reference: api-reference/quixstreams.md
