site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

nav:
 - Current:
    - 'Introduction': 'introduction.md'
 - Previous:
    - 'Introduction': 'Previous/introduction.md'

