site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


exclude_docs: |
  build/*

# TODO: Replace //LINK placeholders everywhere
nav:
  - Introduction: 'introduction.md'
  - Quickstart: 'quickstart.md'
  - Producing Data to Kafka: producer.md
  - Processing & Transforming Data: processing.md
  - Windows & Aggregations: windowing.md # TODO: Add more about the individual functions (esp. reduce())
  - Configuration: configuration.md
  - Advanced Usage:
    - Serialization Formats: advanced/serialization.md
    - Stateful Processing: advanced/stateful-processing.md
    - Managing Kafka Topics: advanced/topics.md
    - Using Producer & Consumer: advanced/producer-consumer.md # TODO: Explain low-level producer and consumer
  - Connecting to Quix Cloud: quix-platform.md # TODO: Review, briefly explain Quix features & where Quix Cloud may help
  - Upgrading Guide:
    - Upgrading from Quix Streams v0.5: upgrading-legacy.md

  - API Docs:
    - StreamingDataFrame API: api-reference/dataframe.md
    - Topics API: api-reference/topics.md
    - Context API: api-reference/context.md
    - Serializers API: api-reference/serialization.md
    - Application API: api-reference/application.md
    - State API: api-reference/state.md
    - Kafka Producer & Consumer API: api-reference/kafka.md
    - Full Reference: api-reference/quixstreams.md
