[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quixstreams"
dynamic = ["version", "dependencies", "optional-dependencies"]
description = "Python library for building stream processing applications with Apache Kafka"
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8, <4"
keywords = ["streaming", "processing", "pipeline", "event", "real-time", "time series", "DataFrame", "Kafka", "Quix"]
authors = [
    { name = "Quix Analytics Ltd", email = "devs@quix.io" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/quixio/quix-streams"

[tool.setuptools.packages.find]
include = ["quixstreams"]
exclude = ["tests*", "docs*", "examples*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "quixstreams.__version__"}


[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  env
)/
'''

[tool.isort]
atomic = true
profile = "black"
line_length = 88


[tool.pytest.ini_options]
minversion = "6.0"
# Ignore manual tests by and some loggers by default
addopts = "--log-disable=urllib3.connectionpool --log-disable=parso --log-disable=docker"

# Print debug logs to the console in tests
log_cli = true
log_cli_level = "DEBUG"
