[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quixstreams"
dynamic = ["version", "dependencies", "optional-dependencies"]
description = "Python library for building stream processing applications with Apache Kafka"
readme = "README.md"
requires-python = ">=3.8, <4"
keywords = ["Quix", "streaming", "pipeline", "Kafka", "Faust", "Confluent", "event", "processing", "real", "time", "series", "Pandas", "DataFrame"]
authors = [
    { name = "Quix Analytics Ltd", email = "devs@quix.io" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://www.quix.io"
Repository = "https://github.com/quixio/quix-streams"
Documentation = "https://quix.io/docs/quix-streams/introduction.html"

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*", "examples*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = {file = ["requirements-dev.txt", "tests/requirements.txt"]}, test = {file = ["tests/requirements.txt"]}}
version = {attr = "quixstreams.__version__"}


[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  env
)/
'''

[tool.isort]
atomic = true
profile = "black"
line_length = 88


[tool.pytest.ini_options]
minversion = "6.0"
# Ignore manual tests by and some loggers by default
addopts = "--log-disable=urllib3.connectionpool --log-disable=parso --log-disable=docker"

# Print debug logs to the console in tests
log_cli = true
log_cli_level = "DEBUG"
